version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: Scripts1/stop1_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts1/start1_container.sh
      timeout: 300
      runas: root